/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CertificatesRouteImport } from './routes/certificates'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificatesIndexRouteImport } from './routes/certificates.index'
import { Route as TestimonialsWallRouteImport } from './routes/testimonials.wall'
import { Route as TestimonialsSubmitRouteImport } from './routes/testimonials.submit'
import { Route as TestimonialsHostRouteImport } from './routes/testimonials.host'
import { Route as TestimonialsHistoryRouteImport } from './routes/testimonials.history'
import { Route as PartyPollsRouteImport } from './routes/party.polls'
import { Route as PartyPollVoterRouteImport } from './routes/party.poll-voter'
import { Route as PartyKahootProjectorRouteImport } from './routes/party.kahoot-projector'
import { Route as PartyKahootPlayerRouteImport } from './routes/party.kahoot-player'
import { Route as PartyKahootHostRouteImport } from './routes/party.kahoot-host'
import { Route as PartyFeelingsRouteImport } from './routes/party.feelings'
import { Route as PartyFeedbackHostRouteImport } from './routes/party.feedback-host'
import { Route as PartyFeedbackClientRouteImport } from './routes/party.feedback-client'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as CertificatesSettingsRouteImport } from './routes/certificates.settings'
import { Route as CertificatesSendRouteImport } from './routes/certificates.send'
import { Route as ApiOgIndexRouteImport } from './routes/api/og/index'
import { Route as PartyPollsHistoryRouteImport } from './routes/party.polls.history'
import { Route as PartyKahootHostHistoryRouteImport } from './routes/party.kahoot-host.history'
import { Route as PartyFeelingsHistoryRouteImport } from './routes/party.feelings.history'
import { Route as PartyFeedbackHostHistoryRouteImport } from './routes/party.feedback-host.history'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as CertificatesVerifyIdRouteImport } from './routes/certificates.verify.$id'
import { Route as ApiOgPollsRouteImport } from './routes/api/og/polls'
import { Route as ApiOgKahootRouteImport } from './routes/api/og/kahoot'
import { Route as ApiOgFeelingsRouteImport } from './routes/api/og/feelings'
import { Route as ApiOgFeedbackRouteImport } from './routes/api/og/feedback'
import { Route as ApiInternalTestimonialsRouteImport } from './routes/api/internal/testimonials'
import { Route as ApiInternalPollsRouteImport } from './routes/api/internal/polls'
import { Route as ApiInternalKahootRouteImport } from './routes/api/internal/kahoot'
import { Route as ApiInternalFeelingsRouteImport } from './routes/api/internal/feelings'
import { Route as ApiInternalFeedbackRouteImport } from './routes/api/internal/feedback'
import { Route as ApiCertificatesSendRouteImport } from './routes/api/certificates/send'
import { Route as ApiCertificatesIssuerRouteImport } from './routes/api/certificates/issuer'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesRoute = CertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesIndexRoute = CertificatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CertificatesRoute,
} as any)
const TestimonialsWallRoute = TestimonialsWallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => TestimonialsRoute,
} as any)
const TestimonialsSubmitRoute = TestimonialsSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => TestimonialsRoute,
} as any)
const TestimonialsHostRoute = TestimonialsHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => TestimonialsRoute,
} as any)
const TestimonialsHistoryRoute = TestimonialsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => TestimonialsRoute,
} as any)
const PartyPollsRoute = PartyPollsRouteImport.update({
  id: '/party/polls',
  path: '/party/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPollVoterRoute = PartyPollVoterRouteImport.update({
  id: '/party/poll-voter',
  path: '/party/poll-voter',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyKahootProjectorRoute = PartyKahootProjectorRouteImport.update({
  id: '/party/kahoot-projector',
  path: '/party/kahoot-projector',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyKahootPlayerRoute = PartyKahootPlayerRouteImport.update({
  id: '/party/kahoot-player',
  path: '/party/kahoot-player',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyKahootHostRoute = PartyKahootHostRouteImport.update({
  id: '/party/kahoot-host',
  path: '/party/kahoot-host',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyFeelingsRoute = PartyFeelingsRouteImport.update({
  id: '/party/feelings',
  path: '/party/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyFeedbackHostRoute = PartyFeedbackHostRouteImport.update({
  id: '/party/feedback-host',
  path: '/party/feedback-host',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyFeedbackClientRoute = PartyFeedbackClientRouteImport.update({
  id: '/party/feedback-client',
  path: '/party/feedback-client',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesSettingsRoute = CertificatesSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => CertificatesRoute,
} as any)
const CertificatesSendRoute = CertificatesSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => CertificatesRoute,
} as any)
const ApiOgIndexRoute = ApiOgIndexRouteImport.update({
  id: '/api/og/',
  path: '/api/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPollsHistoryRoute = PartyPollsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PartyPollsRoute,
} as any)
const PartyKahootHostHistoryRoute = PartyKahootHostHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PartyKahootHostRoute,
} as any)
const PartyFeelingsHistoryRoute = PartyFeelingsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PartyFeelingsRoute,
} as any)
const PartyFeedbackHostHistoryRoute =
  PartyFeedbackHostHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => PartyFeedbackHostRoute,
  } as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesVerifyIdRoute = CertificatesVerifyIdRouteImport.update({
  id: '/verify/$id',
  path: '/verify/$id',
  getParentRoute: () => CertificatesRoute,
} as any)
const ApiOgPollsRoute = ApiOgPollsRouteImport.update({
  id: '/api/og/polls',
  path: '/api/og/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgKahootRoute = ApiOgKahootRouteImport.update({
  id: '/api/og/kahoot',
  path: '/api/og/kahoot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgFeelingsRoute = ApiOgFeelingsRouteImport.update({
  id: '/api/og/feelings',
  path: '/api/og/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgFeedbackRoute = ApiOgFeedbackRouteImport.update({
  id: '/api/og/feedback',
  path: '/api/og/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalTestimonialsRoute = ApiInternalTestimonialsRouteImport.update({
  id: '/api/internal/testimonials',
  path: '/api/internal/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalPollsRoute = ApiInternalPollsRouteImport.update({
  id: '/api/internal/polls',
  path: '/api/internal/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalKahootRoute = ApiInternalKahootRouteImport.update({
  id: '/api/internal/kahoot',
  path: '/api/internal/kahoot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalFeelingsRoute = ApiInternalFeelingsRouteImport.update({
  id: '/api/internal/feelings',
  path: '/api/internal/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalFeedbackRoute = ApiInternalFeedbackRouteImport.update({
  id: '/api/internal/feedback',
  path: '/api/internal/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificatesSendRoute = ApiCertificatesSendRouteImport.update({
  id: '/api/certificates/send',
  path: '/api/certificates/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCertificatesIssuerRoute = ApiCertificatesIssuerRouteImport.update({
  id: '/api/certificates/issuer',
  path: '/api/certificates/issuer',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/mcp': typeof McpRoute
  '/testimonials': typeof TestimonialsRouteWithChildren
  '/certificates/send': typeof CertificatesSendRoute
  '/certificates/settings': typeof CertificatesSettingsRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/party/feedback-client': typeof PartyFeedbackClientRoute
  '/party/feedback-host': typeof PartyFeedbackHostRouteWithChildren
  '/party/feelings': typeof PartyFeelingsRouteWithChildren
  '/party/kahoot-host': typeof PartyKahootHostRouteWithChildren
  '/party/kahoot-player': typeof PartyKahootPlayerRoute
  '/party/kahoot-projector': typeof PartyKahootProjectorRoute
  '/party/poll-voter': typeof PartyPollVoterRoute
  '/party/polls': typeof PartyPollsRouteWithChildren
  '/testimonials/history': typeof TestimonialsHistoryRoute
  '/testimonials/host': typeof TestimonialsHostRoute
  '/testimonials/submit': typeof TestimonialsSubmitRoute
  '/testimonials/wall': typeof TestimonialsWallRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/api/certificates/issuer': typeof ApiCertificatesIssuerRoute
  '/api/certificates/send': typeof ApiCertificatesSendRoute
  '/api/internal/feedback': typeof ApiInternalFeedbackRoute
  '/api/internal/feelings': typeof ApiInternalFeelingsRoute
  '/api/internal/kahoot': typeof ApiInternalKahootRoute
  '/api/internal/polls': typeof ApiInternalPollsRoute
  '/api/internal/testimonials': typeof ApiInternalTestimonialsRoute
  '/api/og/feedback': typeof ApiOgFeedbackRoute
  '/api/og/feelings': typeof ApiOgFeelingsRoute
  '/api/og/kahoot': typeof ApiOgKahootRoute
  '/api/og/polls': typeof ApiOgPollsRoute
  '/certificates/verify/$id': typeof CertificatesVerifyIdRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/party/feedback-host/history': typeof PartyFeedbackHostHistoryRoute
  '/party/feelings/history': typeof PartyFeelingsHistoryRoute
  '/party/kahoot-host/history': typeof PartyKahootHostHistoryRoute
  '/party/polls/history': typeof PartyPollsHistoryRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/mcp': typeof McpRoute
  '/testimonials': typeof TestimonialsRouteWithChildren
  '/certificates/send': typeof CertificatesSendRoute
  '/certificates/settings': typeof CertificatesSettingsRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/party/feedback-client': typeof PartyFeedbackClientRoute
  '/party/feedback-host': typeof PartyFeedbackHostRouteWithChildren
  '/party/feelings': typeof PartyFeelingsRouteWithChildren
  '/party/kahoot-host': typeof PartyKahootHostRouteWithChildren
  '/party/kahoot-player': typeof PartyKahootPlayerRoute
  '/party/kahoot-projector': typeof PartyKahootProjectorRoute
  '/party/poll-voter': typeof PartyPollVoterRoute
  '/party/polls': typeof PartyPollsRouteWithChildren
  '/testimonials/history': typeof TestimonialsHistoryRoute
  '/testimonials/host': typeof TestimonialsHostRoute
  '/testimonials/submit': typeof TestimonialsSubmitRoute
  '/testimonials/wall': typeof TestimonialsWallRoute
  '/certificates': typeof CertificatesIndexRoute
  '/api/certificates/issuer': typeof ApiCertificatesIssuerRoute
  '/api/certificates/send': typeof ApiCertificatesSendRoute
  '/api/internal/feedback': typeof ApiInternalFeedbackRoute
  '/api/internal/feelings': typeof ApiInternalFeelingsRoute
  '/api/internal/kahoot': typeof ApiInternalKahootRoute
  '/api/internal/polls': typeof ApiInternalPollsRoute
  '/api/internal/testimonials': typeof ApiInternalTestimonialsRoute
  '/api/og/feedback': typeof ApiOgFeedbackRoute
  '/api/og/feelings': typeof ApiOgFeelingsRoute
  '/api/og/kahoot': typeof ApiOgKahootRoute
  '/api/og/polls': typeof ApiOgPollsRoute
  '/certificates/verify/$id': typeof CertificatesVerifyIdRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/party/feedback-host/history': typeof PartyFeedbackHostHistoryRoute
  '/party/feelings/history': typeof PartyFeelingsHistoryRoute
  '/party/kahoot-host/history': typeof PartyKahootHostHistoryRoute
  '/party/polls/history': typeof PartyPollsHistoryRoute
  '/api/og': typeof ApiOgIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/certificates': typeof CertificatesRouteWithChildren
  '/mcp': typeof McpRoute
  '/testimonials': typeof TestimonialsRouteWithChildren
  '/certificates/send': typeof CertificatesSendRoute
  '/certificates/settings': typeof CertificatesSettingsRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/party/feedback-client': typeof PartyFeedbackClientRoute
  '/party/feedback-host': typeof PartyFeedbackHostRouteWithChildren
  '/party/feelings': typeof PartyFeelingsRouteWithChildren
  '/party/kahoot-host': typeof PartyKahootHostRouteWithChildren
  '/party/kahoot-player': typeof PartyKahootPlayerRoute
  '/party/kahoot-projector': typeof PartyKahootProjectorRoute
  '/party/poll-voter': typeof PartyPollVoterRoute
  '/party/polls': typeof PartyPollsRouteWithChildren
  '/testimonials/history': typeof TestimonialsHistoryRoute
  '/testimonials/host': typeof TestimonialsHostRoute
  '/testimonials/submit': typeof TestimonialsSubmitRoute
  '/testimonials/wall': typeof TestimonialsWallRoute
  '/certificates/': typeof CertificatesIndexRoute
  '/api/certificates/issuer': typeof ApiCertificatesIssuerRoute
  '/api/certificates/send': typeof ApiCertificatesSendRoute
  '/api/internal/feedback': typeof ApiInternalFeedbackRoute
  '/api/internal/feelings': typeof ApiInternalFeelingsRoute
  '/api/internal/kahoot': typeof ApiInternalKahootRoute
  '/api/internal/polls': typeof ApiInternalPollsRoute
  '/api/internal/testimonials': typeof ApiInternalTestimonialsRoute
  '/api/og/feedback': typeof ApiOgFeedbackRoute
  '/api/og/feelings': typeof ApiOgFeelingsRoute
  '/api/og/kahoot': typeof ApiOgKahootRoute
  '/api/og/polls': typeof ApiOgPollsRoute
  '/certificates/verify/$id': typeof CertificatesVerifyIdRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/party/feedback-host/history': typeof PartyFeedbackHostHistoryRoute
  '/party/feelings/history': typeof PartyFeelingsHistoryRoute
  '/party/kahoot-host/history': typeof PartyKahootHostHistoryRoute
  '/party/polls/history': typeof PartyPollsHistoryRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/certificates'
    | '/mcp'
    | '/testimonials'
    | '/certificates/send'
    | '/certificates/settings'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/table'
    | '/party/feedback-client'
    | '/party/feedback-host'
    | '/party/feelings'
    | '/party/kahoot-host'
    | '/party/kahoot-player'
    | '/party/kahoot-projector'
    | '/party/poll-voter'
    | '/party/polls'
    | '/testimonials/history'
    | '/testimonials/host'
    | '/testimonials/submit'
    | '/testimonials/wall'
    | '/certificates/'
    | '/api/certificates/issuer'
    | '/api/certificates/send'
    | '/api/internal/feedback'
    | '/api/internal/feelings'
    | '/api/internal/kahoot'
    | '/api/internal/polls'
    | '/api/internal/testimonials'
    | '/api/og/feedback'
    | '/api/og/feelings'
    | '/api/og/kahoot'
    | '/api/og/polls'
    | '/certificates/verify/$id'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/party/feedback-host/history'
    | '/party/feelings/history'
    | '/party/kahoot-host/history'
    | '/party/polls/history'
    | '/api/og/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/mcp'
    | '/testimonials'
    | '/certificates/send'
    | '/certificates/settings'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/table'
    | '/party/feedback-client'
    | '/party/feedback-host'
    | '/party/feelings'
    | '/party/kahoot-host'
    | '/party/kahoot-player'
    | '/party/kahoot-projector'
    | '/party/poll-voter'
    | '/party/polls'
    | '/testimonials/history'
    | '/testimonials/host'
    | '/testimonials/submit'
    | '/testimonials/wall'
    | '/certificates'
    | '/api/certificates/issuer'
    | '/api/certificates/send'
    | '/api/internal/feedback'
    | '/api/internal/feelings'
    | '/api/internal/kahoot'
    | '/api/internal/polls'
    | '/api/internal/testimonials'
    | '/api/og/feedback'
    | '/api/og/feelings'
    | '/api/og/kahoot'
    | '/api/og/polls'
    | '/certificates/verify/$id'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/party/feedback-host/history'
    | '/party/feelings/history'
    | '/party/kahoot-host/history'
    | '/party/polls/history'
    | '/api/og'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/certificates'
    | '/mcp'
    | '/testimonials'
    | '/certificates/send'
    | '/certificates/settings'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/table'
    | '/party/feedback-client'
    | '/party/feedback-host'
    | '/party/feelings'
    | '/party/kahoot-host'
    | '/party/kahoot-player'
    | '/party/kahoot-projector'
    | '/party/poll-voter'
    | '/party/polls'
    | '/testimonials/history'
    | '/testimonials/host'
    | '/testimonials/submit'
    | '/testimonials/wall'
    | '/certificates/'
    | '/api/certificates/issuer'
    | '/api/certificates/send'
    | '/api/internal/feedback'
    | '/api/internal/feelings'
    | '/api/internal/kahoot'
    | '/api/internal/polls'
    | '/api/internal/testimonials'
    | '/api/og/feedback'
    | '/api/og/feelings'
    | '/api/og/kahoot'
    | '/api/og/polls'
    | '/certificates/verify/$id'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/party/feedback-host/history'
    | '/party/feelings/history'
    | '/party/kahoot-host/history'
    | '/party/polls/history'
    | '/api/og/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  CertificatesRoute: typeof CertificatesRouteWithChildren
  McpRoute: typeof McpRoute
  TestimonialsRoute: typeof TestimonialsRouteWithChildren
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTableRoute: typeof DemoTableRoute
  PartyFeedbackClientRoute: typeof PartyFeedbackClientRoute
  PartyFeedbackHostRoute: typeof PartyFeedbackHostRouteWithChildren
  PartyFeelingsRoute: typeof PartyFeelingsRouteWithChildren
  PartyKahootHostRoute: typeof PartyKahootHostRouteWithChildren
  PartyKahootPlayerRoute: typeof PartyKahootPlayerRoute
  PartyKahootProjectorRoute: typeof PartyKahootProjectorRoute
  PartyPollVoterRoute: typeof PartyPollVoterRoute
  PartyPollsRoute: typeof PartyPollsRouteWithChildren
  ApiCertificatesIssuerRoute: typeof ApiCertificatesIssuerRoute
  ApiCertificatesSendRoute: typeof ApiCertificatesSendRoute
  ApiInternalFeedbackRoute: typeof ApiInternalFeedbackRoute
  ApiInternalFeelingsRoute: typeof ApiInternalFeelingsRoute
  ApiInternalKahootRoute: typeof ApiInternalKahootRoute
  ApiInternalPollsRoute: typeof ApiInternalPollsRoute
  ApiInternalTestimonialsRoute: typeof ApiInternalTestimonialsRoute
  ApiOgFeedbackRoute: typeof ApiOgFeedbackRoute
  ApiOgFeelingsRoute: typeof ApiOgFeelingsRoute
  ApiOgKahootRoute: typeof ApiOgKahootRoute
  ApiOgPollsRoute: typeof ApiOgPollsRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiOgIndexRoute: typeof ApiOgIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates': {
      id: '/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof CertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/': {
      id: '/certificates/'
      path: '/'
      fullPath: '/certificates/'
      preLoaderRoute: typeof CertificatesIndexRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/testimonials/wall': {
      id: '/testimonials/wall'
      path: '/wall'
      fullPath: '/testimonials/wall'
      preLoaderRoute: typeof TestimonialsWallRouteImport
      parentRoute: typeof TestimonialsRoute
    }
    '/testimonials/submit': {
      id: '/testimonials/submit'
      path: '/submit'
      fullPath: '/testimonials/submit'
      preLoaderRoute: typeof TestimonialsSubmitRouteImport
      parentRoute: typeof TestimonialsRoute
    }
    '/testimonials/host': {
      id: '/testimonials/host'
      path: '/host'
      fullPath: '/testimonials/host'
      preLoaderRoute: typeof TestimonialsHostRouteImport
      parentRoute: typeof TestimonialsRoute
    }
    '/testimonials/history': {
      id: '/testimonials/history'
      path: '/history'
      fullPath: '/testimonials/history'
      preLoaderRoute: typeof TestimonialsHistoryRouteImport
      parentRoute: typeof TestimonialsRoute
    }
    '/party/polls': {
      id: '/party/polls'
      path: '/party/polls'
      fullPath: '/party/polls'
      preLoaderRoute: typeof PartyPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/poll-voter': {
      id: '/party/poll-voter'
      path: '/party/poll-voter'
      fullPath: '/party/poll-voter'
      preLoaderRoute: typeof PartyPollVoterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/kahoot-projector': {
      id: '/party/kahoot-projector'
      path: '/party/kahoot-projector'
      fullPath: '/party/kahoot-projector'
      preLoaderRoute: typeof PartyKahootProjectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/kahoot-player': {
      id: '/party/kahoot-player'
      path: '/party/kahoot-player'
      fullPath: '/party/kahoot-player'
      preLoaderRoute: typeof PartyKahootPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/kahoot-host': {
      id: '/party/kahoot-host'
      path: '/party/kahoot-host'
      fullPath: '/party/kahoot-host'
      preLoaderRoute: typeof PartyKahootHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/feelings': {
      id: '/party/feelings'
      path: '/party/feelings'
      fullPath: '/party/feelings'
      preLoaderRoute: typeof PartyFeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/feedback-host': {
      id: '/party/feedback-host'
      path: '/party/feedback-host'
      fullPath: '/party/feedback-host'
      preLoaderRoute: typeof PartyFeedbackHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/feedback-client': {
      id: '/party/feedback-client'
      path: '/party/feedback-client'
      fullPath: '/party/feedback-client'
      preLoaderRoute: typeof PartyFeedbackClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/settings': {
      id: '/certificates/settings'
      path: '/settings'
      fullPath: '/certificates/settings'
      preLoaderRoute: typeof CertificatesSettingsRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/certificates/send': {
      id: '/certificates/send'
      path: '/send'
      fullPath: '/certificates/send'
      preLoaderRoute: typeof CertificatesSendRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/api/og/': {
      id: '/api/og/'
      path: '/api/og'
      fullPath: '/api/og/'
      preLoaderRoute: typeof ApiOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/polls/history': {
      id: '/party/polls/history'
      path: '/history'
      fullPath: '/party/polls/history'
      preLoaderRoute: typeof PartyPollsHistoryRouteImport
      parentRoute: typeof PartyPollsRoute
    }
    '/party/kahoot-host/history': {
      id: '/party/kahoot-host/history'
      path: '/history'
      fullPath: '/party/kahoot-host/history'
      preLoaderRoute: typeof PartyKahootHostHistoryRouteImport
      parentRoute: typeof PartyKahootHostRoute
    }
    '/party/feelings/history': {
      id: '/party/feelings/history'
      path: '/history'
      fullPath: '/party/feelings/history'
      preLoaderRoute: typeof PartyFeelingsHistoryRouteImport
      parentRoute: typeof PartyFeelingsRoute
    }
    '/party/feedback-host/history': {
      id: '/party/feedback-host/history'
      path: '/history'
      fullPath: '/party/feedback-host/history'
      preLoaderRoute: typeof PartyFeedbackHostHistoryRouteImport
      parentRoute: typeof PartyFeedbackHostRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/verify/$id': {
      id: '/certificates/verify/$id'
      path: '/verify/$id'
      fullPath: '/certificates/verify/$id'
      preLoaderRoute: typeof CertificatesVerifyIdRouteImport
      parentRoute: typeof CertificatesRoute
    }
    '/api/og/polls': {
      id: '/api/og/polls'
      path: '/api/og/polls'
      fullPath: '/api/og/polls'
      preLoaderRoute: typeof ApiOgPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/kahoot': {
      id: '/api/og/kahoot'
      path: '/api/og/kahoot'
      fullPath: '/api/og/kahoot'
      preLoaderRoute: typeof ApiOgKahootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/feelings': {
      id: '/api/og/feelings'
      path: '/api/og/feelings'
      fullPath: '/api/og/feelings'
      preLoaderRoute: typeof ApiOgFeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/feedback': {
      id: '/api/og/feedback'
      path: '/api/og/feedback'
      fullPath: '/api/og/feedback'
      preLoaderRoute: typeof ApiOgFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/testimonials': {
      id: '/api/internal/testimonials'
      path: '/api/internal/testimonials'
      fullPath: '/api/internal/testimonials'
      preLoaderRoute: typeof ApiInternalTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/polls': {
      id: '/api/internal/polls'
      path: '/api/internal/polls'
      fullPath: '/api/internal/polls'
      preLoaderRoute: typeof ApiInternalPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/kahoot': {
      id: '/api/internal/kahoot'
      path: '/api/internal/kahoot'
      fullPath: '/api/internal/kahoot'
      preLoaderRoute: typeof ApiInternalKahootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/feelings': {
      id: '/api/internal/feelings'
      path: '/api/internal/feelings'
      fullPath: '/api/internal/feelings'
      preLoaderRoute: typeof ApiInternalFeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/feedback': {
      id: '/api/internal/feedback'
      path: '/api/internal/feedback'
      fullPath: '/api/internal/feedback'
      preLoaderRoute: typeof ApiInternalFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates/send': {
      id: '/api/certificates/send'
      path: '/api/certificates/send'
      fullPath: '/api/certificates/send'
      preLoaderRoute: typeof ApiCertificatesSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/certificates/issuer': {
      id: '/api/certificates/issuer'
      path: '/api/certificates/issuer'
      fullPath: '/api/certificates/issuer'
      preLoaderRoute: typeof ApiCertificatesIssuerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CertificatesRouteChildren {
  CertificatesSendRoute: typeof CertificatesSendRoute
  CertificatesSettingsRoute: typeof CertificatesSettingsRoute
  CertificatesIndexRoute: typeof CertificatesIndexRoute
  CertificatesVerifyIdRoute: typeof CertificatesVerifyIdRoute
}

const CertificatesRouteChildren: CertificatesRouteChildren = {
  CertificatesSendRoute: CertificatesSendRoute,
  CertificatesSettingsRoute: CertificatesSettingsRoute,
  CertificatesIndexRoute: CertificatesIndexRoute,
  CertificatesVerifyIdRoute: CertificatesVerifyIdRoute,
}

const CertificatesRouteWithChildren = CertificatesRoute._addFileChildren(
  CertificatesRouteChildren,
)

interface TestimonialsRouteChildren {
  TestimonialsHistoryRoute: typeof TestimonialsHistoryRoute
  TestimonialsHostRoute: typeof TestimonialsHostRoute
  TestimonialsSubmitRoute: typeof TestimonialsSubmitRoute
  TestimonialsWallRoute: typeof TestimonialsWallRoute
}

const TestimonialsRouteChildren: TestimonialsRouteChildren = {
  TestimonialsHistoryRoute: TestimonialsHistoryRoute,
  TestimonialsHostRoute: TestimonialsHostRoute,
  TestimonialsSubmitRoute: TestimonialsSubmitRoute,
  TestimonialsWallRoute: TestimonialsWallRoute,
}

const TestimonialsRouteWithChildren = TestimonialsRoute._addFileChildren(
  TestimonialsRouteChildren,
)

interface PartyFeedbackHostRouteChildren {
  PartyFeedbackHostHistoryRoute: typeof PartyFeedbackHostHistoryRoute
}

const PartyFeedbackHostRouteChildren: PartyFeedbackHostRouteChildren = {
  PartyFeedbackHostHistoryRoute: PartyFeedbackHostHistoryRoute,
}

const PartyFeedbackHostRouteWithChildren =
  PartyFeedbackHostRoute._addFileChildren(PartyFeedbackHostRouteChildren)

interface PartyFeelingsRouteChildren {
  PartyFeelingsHistoryRoute: typeof PartyFeelingsHistoryRoute
}

const PartyFeelingsRouteChildren: PartyFeelingsRouteChildren = {
  PartyFeelingsHistoryRoute: PartyFeelingsHistoryRoute,
}

const PartyFeelingsRouteWithChildren = PartyFeelingsRoute._addFileChildren(
  PartyFeelingsRouteChildren,
)

interface PartyKahootHostRouteChildren {
  PartyKahootHostHistoryRoute: typeof PartyKahootHostHistoryRoute
}

const PartyKahootHostRouteChildren: PartyKahootHostRouteChildren = {
  PartyKahootHostHistoryRoute: PartyKahootHostHistoryRoute,
}

const PartyKahootHostRouteWithChildren = PartyKahootHostRoute._addFileChildren(
  PartyKahootHostRouteChildren,
)

interface PartyPollsRouteChildren {
  PartyPollsHistoryRoute: typeof PartyPollsHistoryRoute
}

const PartyPollsRouteChildren: PartyPollsRouteChildren = {
  PartyPollsHistoryRoute: PartyPollsHistoryRoute,
}

const PartyPollsRouteWithChildren = PartyPollsRoute._addFileChildren(
  PartyPollsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  CertificatesRoute: CertificatesRouteWithChildren,
  McpRoute: McpRoute,
  TestimonialsRoute: TestimonialsRouteWithChildren,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTableRoute: DemoTableRoute,
  PartyFeedbackClientRoute: PartyFeedbackClientRoute,
  PartyFeedbackHostRoute: PartyFeedbackHostRouteWithChildren,
  PartyFeelingsRoute: PartyFeelingsRouteWithChildren,
  PartyKahootHostRoute: PartyKahootHostRouteWithChildren,
  PartyKahootPlayerRoute: PartyKahootPlayerRoute,
  PartyKahootProjectorRoute: PartyKahootProjectorRoute,
  PartyPollVoterRoute: PartyPollVoterRoute,
  PartyPollsRoute: PartyPollsRouteWithChildren,
  ApiCertificatesIssuerRoute: ApiCertificatesIssuerRoute,
  ApiCertificatesSendRoute: ApiCertificatesSendRoute,
  ApiInternalFeedbackRoute: ApiInternalFeedbackRoute,
  ApiInternalFeelingsRoute: ApiInternalFeelingsRoute,
  ApiInternalKahootRoute: ApiInternalKahootRoute,
  ApiInternalPollsRoute: ApiInternalPollsRoute,
  ApiInternalTestimonialsRoute: ApiInternalTestimonialsRoute,
  ApiOgFeedbackRoute: ApiOgFeedbackRoute,
  ApiOgFeelingsRoute: ApiOgFeelingsRoute,
  ApiOgKahootRoute: ApiOgKahootRoute,
  ApiOgPollsRoute: ApiOgPollsRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiOgIndexRoute: ApiOgIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
