/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestimonialsWallRouteImport } from './routes/testimonials.wall'
import { Route as TestimonialsSubmitRouteImport } from './routes/testimonials.submit'
import { Route as PartyPollVoterRouteImport } from './routes/party.poll-voter'
import { Route as PartyKahootProjectorRouteImport } from './routes/party.kahoot-projector'
import { Route as PartyKahootPlayerRouteImport } from './routes/party.kahoot-player'
import { Route as PartyFeedbackClientRouteImport } from './routes/party.feedback-client'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as AuthedTestimonialsRouteImport } from './routes/_authed/testimonials'
import { Route as AuthedScheduleRouteImport } from './routes/_authed/schedule'
import { Route as AuthedCertificatesRouteImport } from './routes/_authed/certificates'
import { Route as ApiOgIndexRouteImport } from './routes/api/og/index'
import { Route as AuthedTestimonialsIndexRouteImport } from './routes/_authed/testimonials.index'
import { Route as AuthedScheduleIndexRouteImport } from './routes/_authed/schedule.index'
import { Route as AuthedCertificatesIndexRouteImport } from './routes/_authed/certificates.index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as CertificatesVerifyIdRouteImport } from './routes/certificates.verify.$id'
import { Route as ApiOgTestimonialsRouteImport } from './routes/api/og/testimonials'
import { Route as ApiOgPollsRouteImport } from './routes/api/og/polls'
import { Route as ApiOgKahootRouteImport } from './routes/api/og/kahoot'
import { Route as ApiOgFeelingsRouteImport } from './routes/api/og/feelings'
import { Route as ApiOgFeedbackRouteImport } from './routes/api/og/feedback'
import { Route as ApiOgCertificatesRouteImport } from './routes/api/og/certificates'
import { Route as ApiInternalTestimonialsRouteImport } from './routes/api/internal/testimonials'
import { Route as ApiInternalPollsRouteImport } from './routes/api/internal/polls'
import { Route as ApiInternalKahootRouteImport } from './routes/api/internal/kahoot'
import { Route as ApiInternalFeelingsRouteImport } from './routes/api/internal/feelings'
import { Route as ApiInternalFeedbackRouteImport } from './routes/api/internal/feedback'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthedTestimonialsHostRouteImport } from './routes/_authed/testimonials.host'
import { Route as AuthedTestimonialsHistoryRouteImport } from './routes/_authed/testimonials.history'
import { Route as AuthedScheduleNewRouteImport } from './routes/_authed/schedule.new'
import { Route as AuthedPartyPollsRouteImport } from './routes/_authed/party.polls'
import { Route as AuthedPartyKahootHostRouteImport } from './routes/_authed/party.kahoot-host'
import { Route as AuthedPartyFeelingsRouteImport } from './routes/_authed/party.feelings'
import { Route as AuthedPartyFeedbackHostRouteImport } from './routes/_authed/party.feedback-host'
import { Route as AuthedCertificatesSettingsRouteImport } from './routes/_authed/certificates.settings'
import { Route as AuthedCertificatesSendRouteImport } from './routes/_authed/certificates.send'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as AuthedPartyPollsIndexRouteImport } from './routes/_authed/party.polls.index'
import { Route as AuthedPartyKahootHostIndexRouteImport } from './routes/_authed/party.kahoot-host.index'
import { Route as AuthedPartyFeelingsIndexRouteImport } from './routes/_authed/party.feelings.index'
import { Route as AuthedPartyFeedbackHostIndexRouteImport } from './routes/_authed/party.feedback-host.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'
import { Route as AuthedPartyPollsHistoryRouteImport } from './routes/_authed/party.polls.history'
import { Route as AuthedPartyKahootHostHistoryRouteImport } from './routes/_authed/party.kahoot-host.history'
import { Route as AuthedPartyFeelingsHistoryRouteImport } from './routes/_authed/party.feelings.history'
import { Route as AuthedPartyFeedbackHostHistoryRouteImport } from './routes/_authed/party.feedback-host.history'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsWallRoute = TestimonialsWallRouteImport.update({
  id: '/testimonials/wall',
  path: '/testimonials/wall',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsSubmitRoute = TestimonialsSubmitRouteImport.update({
  id: '/testimonials/submit',
  path: '/testimonials/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPollVoterRoute = PartyPollVoterRouteImport.update({
  id: '/party/poll-voter',
  path: '/party/poll-voter',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyKahootProjectorRoute = PartyKahootProjectorRouteImport.update({
  id: '/party/kahoot-projector',
  path: '/party/kahoot-projector',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyKahootPlayerRoute = PartyKahootPlayerRouteImport.update({
  id: '/party/kahoot-player',
  path: '/party/kahoot-player',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyFeedbackClientRoute = PartyFeedbackClientRouteImport.update({
  id: '/party/feedback-client',
  path: '/party/feedback-client',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTestimonialsRoute = AuthedTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedScheduleRoute = AuthedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCertificatesRoute = AuthedCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiOgIndexRoute = ApiOgIndexRouteImport.update({
  id: '/api/og/',
  path: '/api/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTestimonialsIndexRoute = AuthedTestimonialsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedTestimonialsRoute,
} as any)
const AuthedScheduleIndexRoute = AuthedScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedScheduleRoute,
} as any)
const AuthedCertificatesIndexRoute = AuthedCertificatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedCertificatesRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatesVerifyIdRoute = CertificatesVerifyIdRouteImport.update({
  id: '/certificates/verify/$id',
  path: '/certificates/verify/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgTestimonialsRoute = ApiOgTestimonialsRouteImport.update({
  id: '/api/og/testimonials',
  path: '/api/og/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPollsRoute = ApiOgPollsRouteImport.update({
  id: '/api/og/polls',
  path: '/api/og/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgKahootRoute = ApiOgKahootRouteImport.update({
  id: '/api/og/kahoot',
  path: '/api/og/kahoot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgFeelingsRoute = ApiOgFeelingsRouteImport.update({
  id: '/api/og/feelings',
  path: '/api/og/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgFeedbackRoute = ApiOgFeedbackRouteImport.update({
  id: '/api/og/feedback',
  path: '/api/og/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgCertificatesRoute = ApiOgCertificatesRouteImport.update({
  id: '/api/og/certificates',
  path: '/api/og/certificates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalTestimonialsRoute = ApiInternalTestimonialsRouteImport.update({
  id: '/api/internal/testimonials',
  path: '/api/internal/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalPollsRoute = ApiInternalPollsRouteImport.update({
  id: '/api/internal/polls',
  path: '/api/internal/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalKahootRoute = ApiInternalKahootRouteImport.update({
  id: '/api/internal/kahoot',
  path: '/api/internal/kahoot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalFeelingsRoute = ApiInternalFeelingsRouteImport.update({
  id: '/api/internal/feelings',
  path: '/api/internal/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInternalFeedbackRoute = ApiInternalFeedbackRouteImport.update({
  id: '/api/internal/feedback',
  path: '/api/internal/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTestimonialsHostRoute = AuthedTestimonialsHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => AuthedTestimonialsRoute,
} as any)
const AuthedTestimonialsHistoryRoute =
  AuthedTestimonialsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedTestimonialsRoute,
  } as any)
const AuthedScheduleNewRoute = AuthedScheduleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedScheduleRoute,
} as any)
const AuthedPartyPollsRoute = AuthedPartyPollsRouteImport.update({
  id: '/party/polls',
  path: '/party/polls',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPartyKahootHostRoute = AuthedPartyKahootHostRouteImport.update({
  id: '/party/kahoot-host',
  path: '/party/kahoot-host',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPartyFeelingsRoute = AuthedPartyFeelingsRouteImport.update({
  id: '/party/feelings',
  path: '/party/feelings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPartyFeedbackHostRoute = AuthedPartyFeedbackHostRouteImport.update({
  id: '/party/feedback-host',
  path: '/party/feedback-host',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCertificatesSettingsRoute =
  AuthedCertificatesSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedCertificatesRoute,
  } as any)
const AuthedCertificatesSendRoute = AuthedCertificatesSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AuthedCertificatesRoute,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPartyPollsIndexRoute = AuthedPartyPollsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedPartyPollsRoute,
} as any)
const AuthedPartyKahootHostIndexRoute =
  AuthedPartyKahootHostIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedPartyKahootHostRoute,
  } as any)
const AuthedPartyFeelingsIndexRoute =
  AuthedPartyFeelingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedPartyFeelingsRoute,
  } as any)
const AuthedPartyFeedbackHostIndexRoute =
  AuthedPartyFeedbackHostIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedPartyFeedbackHostRoute,
  } as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedPartyPollsHistoryRoute = AuthedPartyPollsHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthedPartyPollsRoute,
} as any)
const AuthedPartyKahootHostHistoryRoute =
  AuthedPartyKahootHostHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedPartyKahootHostRoute,
  } as any)
const AuthedPartyFeelingsHistoryRoute =
  AuthedPartyFeelingsHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedPartyFeelingsRoute,
  } as any)
const AuthedPartyFeedbackHostHistoryRoute =
  AuthedPartyFeedbackHostHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthedPartyFeedbackHostRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/certificates': typeof AuthedCertificatesRouteWithChildren
  '/schedule': typeof AuthedScheduleRouteWithChildren
  '/testimonials': typeof AuthedTestimonialsRouteWithChildren
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/party/feedback-client': typeof PartyFeedbackClientRoute
  '/party/kahoot-player': typeof PartyKahootPlayerRoute
  '/party/kahoot-projector': typeof PartyKahootProjectorRoute
  '/party/poll-voter': typeof PartyPollVoterRoute
  '/testimonials/submit': typeof TestimonialsSubmitRoute
  '/testimonials/wall': typeof TestimonialsWallRoute
  '/certificates/send': typeof AuthedCertificatesSendRoute
  '/certificates/settings': typeof AuthedCertificatesSettingsRoute
  '/party/feedback-host': typeof AuthedPartyFeedbackHostRouteWithChildren
  '/party/feelings': typeof AuthedPartyFeelingsRouteWithChildren
  '/party/kahoot-host': typeof AuthedPartyKahootHostRouteWithChildren
  '/party/polls': typeof AuthedPartyPollsRouteWithChildren
  '/schedule/new': typeof AuthedScheduleNewRoute
  '/testimonials/history': typeof AuthedTestimonialsHistoryRoute
  '/testimonials/host': typeof AuthedTestimonialsHostRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/feedback': typeof ApiInternalFeedbackRoute
  '/api/internal/feelings': typeof ApiInternalFeelingsRoute
  '/api/internal/kahoot': typeof ApiInternalKahootRoute
  '/api/internal/polls': typeof ApiInternalPollsRoute
  '/api/internal/testimonials': typeof ApiInternalTestimonialsRoute
  '/api/og/certificates': typeof ApiOgCertificatesRoute
  '/api/og/feedback': typeof ApiOgFeedbackRoute
  '/api/og/feelings': typeof ApiOgFeelingsRoute
  '/api/og/kahoot': typeof ApiOgKahootRoute
  '/api/og/polls': typeof ApiOgPollsRoute
  '/api/og/testimonials': typeof ApiOgTestimonialsRoute
  '/certificates/verify/$id': typeof CertificatesVerifyIdRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/certificates/': typeof AuthedCertificatesIndexRoute
  '/schedule/': typeof AuthedScheduleIndexRoute
  '/testimonials/': typeof AuthedTestimonialsIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/party/feedback-host/history': typeof AuthedPartyFeedbackHostHistoryRoute
  '/party/feelings/history': typeof AuthedPartyFeelingsHistoryRoute
  '/party/kahoot-host/history': typeof AuthedPartyKahootHostHistoryRoute
  '/party/polls/history': typeof AuthedPartyPollsHistoryRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/party/feedback-host/': typeof AuthedPartyFeedbackHostIndexRoute
  '/party/feelings/': typeof AuthedPartyFeelingsIndexRoute
  '/party/kahoot-host/': typeof AuthedPartyKahootHostIndexRoute
  '/party/polls/': typeof AuthedPartyPollsIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/party/feedback-client': typeof PartyFeedbackClientRoute
  '/party/kahoot-player': typeof PartyKahootPlayerRoute
  '/party/kahoot-projector': typeof PartyKahootProjectorRoute
  '/party/poll-voter': typeof PartyPollVoterRoute
  '/testimonials/submit': typeof TestimonialsSubmitRoute
  '/testimonials/wall': typeof TestimonialsWallRoute
  '/certificates/send': typeof AuthedCertificatesSendRoute
  '/certificates/settings': typeof AuthedCertificatesSettingsRoute
  '/schedule/new': typeof AuthedScheduleNewRoute
  '/testimonials/history': typeof AuthedTestimonialsHistoryRoute
  '/testimonials/host': typeof AuthedTestimonialsHostRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/feedback': typeof ApiInternalFeedbackRoute
  '/api/internal/feelings': typeof ApiInternalFeelingsRoute
  '/api/internal/kahoot': typeof ApiInternalKahootRoute
  '/api/internal/polls': typeof ApiInternalPollsRoute
  '/api/internal/testimonials': typeof ApiInternalTestimonialsRoute
  '/api/og/certificates': typeof ApiOgCertificatesRoute
  '/api/og/feedback': typeof ApiOgFeedbackRoute
  '/api/og/feelings': typeof ApiOgFeelingsRoute
  '/api/og/kahoot': typeof ApiOgKahootRoute
  '/api/og/polls': typeof ApiOgPollsRoute
  '/api/og/testimonials': typeof ApiOgTestimonialsRoute
  '/certificates/verify/$id': typeof CertificatesVerifyIdRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/certificates': typeof AuthedCertificatesIndexRoute
  '/schedule': typeof AuthedScheduleIndexRoute
  '/testimonials': typeof AuthedTestimonialsIndexRoute
  '/api/og': typeof ApiOgIndexRoute
  '/party/feedback-host/history': typeof AuthedPartyFeedbackHostHistoryRoute
  '/party/feelings/history': typeof AuthedPartyFeelingsHistoryRoute
  '/party/kahoot-host/history': typeof AuthedPartyKahootHostHistoryRoute
  '/party/polls/history': typeof AuthedPartyPollsHistoryRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/party/feedback-host': typeof AuthedPartyFeedbackHostIndexRoute
  '/party/feelings': typeof AuthedPartyFeelingsIndexRoute
  '/party/kahoot-host': typeof AuthedPartyKahootHostIndexRoute
  '/party/polls': typeof AuthedPartyPollsIndexRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/mcp': typeof McpRoute
  '/_authed/certificates': typeof AuthedCertificatesRouteWithChildren
  '/_authed/schedule': typeof AuthedScheduleRouteWithChildren
  '/_authed/testimonials': typeof AuthedTestimonialsRouteWithChildren
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/party/feedback-client': typeof PartyFeedbackClientRoute
  '/party/kahoot-player': typeof PartyKahootPlayerRoute
  '/party/kahoot-projector': typeof PartyKahootProjectorRoute
  '/party/poll-voter': typeof PartyPollVoterRoute
  '/testimonials/submit': typeof TestimonialsSubmitRoute
  '/testimonials/wall': typeof TestimonialsWallRoute
  '/_authed/certificates/send': typeof AuthedCertificatesSendRoute
  '/_authed/certificates/settings': typeof AuthedCertificatesSettingsRoute
  '/_authed/party/feedback-host': typeof AuthedPartyFeedbackHostRouteWithChildren
  '/_authed/party/feelings': typeof AuthedPartyFeelingsRouteWithChildren
  '/_authed/party/kahoot-host': typeof AuthedPartyKahootHostRouteWithChildren
  '/_authed/party/polls': typeof AuthedPartyPollsRouteWithChildren
  '/_authed/schedule/new': typeof AuthedScheduleNewRoute
  '/_authed/testimonials/history': typeof AuthedTestimonialsHistoryRoute
  '/_authed/testimonials/host': typeof AuthedTestimonialsHostRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/internal/feedback': typeof ApiInternalFeedbackRoute
  '/api/internal/feelings': typeof ApiInternalFeelingsRoute
  '/api/internal/kahoot': typeof ApiInternalKahootRoute
  '/api/internal/polls': typeof ApiInternalPollsRoute
  '/api/internal/testimonials': typeof ApiInternalTestimonialsRoute
  '/api/og/certificates': typeof ApiOgCertificatesRoute
  '/api/og/feedback': typeof ApiOgFeedbackRoute
  '/api/og/feelings': typeof ApiOgFeelingsRoute
  '/api/og/kahoot': typeof ApiOgKahootRoute
  '/api/og/polls': typeof ApiOgPollsRoute
  '/api/og/testimonials': typeof ApiOgTestimonialsRoute
  '/certificates/verify/$id': typeof CertificatesVerifyIdRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/_authed/certificates/': typeof AuthedCertificatesIndexRoute
  '/_authed/schedule/': typeof AuthedScheduleIndexRoute
  '/_authed/testimonials/': typeof AuthedTestimonialsIndexRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/_authed/party/feedback-host/history': typeof AuthedPartyFeedbackHostHistoryRoute
  '/_authed/party/feelings/history': typeof AuthedPartyFeelingsHistoryRoute
  '/_authed/party/kahoot-host/history': typeof AuthedPartyKahootHostHistoryRoute
  '/_authed/party/polls/history': typeof AuthedPartyPollsHistoryRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/_authed/party/feedback-host/': typeof AuthedPartyFeedbackHostIndexRoute
  '/_authed/party/feelings/': typeof AuthedPartyFeelingsIndexRoute
  '/_authed/party/kahoot-host/': typeof AuthedPartyKahootHostIndexRoute
  '/_authed/party/polls/': typeof AuthedPartyPollsIndexRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/mcp'
    | '/certificates'
    | '/schedule'
    | '/testimonials'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/table'
    | '/party/feedback-client'
    | '/party/kahoot-player'
    | '/party/kahoot-projector'
    | '/party/poll-voter'
    | '/testimonials/submit'
    | '/testimonials/wall'
    | '/certificates/send'
    | '/certificates/settings'
    | '/party/feedback-host'
    | '/party/feelings'
    | '/party/kahoot-host'
    | '/party/polls'
    | '/schedule/new'
    | '/testimonials/history'
    | '/testimonials/host'
    | '/api/auth/$'
    | '/api/internal/feedback'
    | '/api/internal/feelings'
    | '/api/internal/kahoot'
    | '/api/internal/polls'
    | '/api/internal/testimonials'
    | '/api/og/certificates'
    | '/api/og/feedback'
    | '/api/og/feelings'
    | '/api/og/kahoot'
    | '/api/og/polls'
    | '/api/og/testimonials'
    | '/certificates/verify/$id'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/certificates/'
    | '/schedule/'
    | '/testimonials/'
    | '/api/og/'
    | '/party/feedback-host/history'
    | '/party/feelings/history'
    | '/party/kahoot-host/history'
    | '/party/polls/history'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/party/feedback-host/'
    | '/party/feelings/'
    | '/party/kahoot-host/'
    | '/party/polls/'
    | '/demo/start/ssr/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/mcp'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/table'
    | '/party/feedback-client'
    | '/party/kahoot-player'
    | '/party/kahoot-projector'
    | '/party/poll-voter'
    | '/testimonials/submit'
    | '/testimonials/wall'
    | '/certificates/send'
    | '/certificates/settings'
    | '/schedule/new'
    | '/testimonials/history'
    | '/testimonials/host'
    | '/api/auth/$'
    | '/api/internal/feedback'
    | '/api/internal/feelings'
    | '/api/internal/kahoot'
    | '/api/internal/polls'
    | '/api/internal/testimonials'
    | '/api/og/certificates'
    | '/api/og/feedback'
    | '/api/og/feelings'
    | '/api/og/kahoot'
    | '/api/og/polls'
    | '/api/og/testimonials'
    | '/certificates/verify/$id'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/certificates'
    | '/schedule'
    | '/testimonials'
    | '/api/og'
    | '/party/feedback-host/history'
    | '/party/feelings/history'
    | '/party/kahoot-host/history'
    | '/party/polls/history'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/party/feedback-host'
    | '/party/feelings'
    | '/party/kahoot-host'
    | '/party/polls'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_authed'
    | '/login'
    | '/mcp'
    | '/_authed/certificates'
    | '/_authed/schedule'
    | '/_authed/testimonials'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/table'
    | '/party/feedback-client'
    | '/party/kahoot-player'
    | '/party/kahoot-projector'
    | '/party/poll-voter'
    | '/testimonials/submit'
    | '/testimonials/wall'
    | '/_authed/certificates/send'
    | '/_authed/certificates/settings'
    | '/_authed/party/feedback-host'
    | '/_authed/party/feelings'
    | '/_authed/party/kahoot-host'
    | '/_authed/party/polls'
    | '/_authed/schedule/new'
    | '/_authed/testimonials/history'
    | '/_authed/testimonials/host'
    | '/api/auth/$'
    | '/api/internal/feedback'
    | '/api/internal/feelings'
    | '/api/internal/kahoot'
    | '/api/internal/polls'
    | '/api/internal/testimonials'
    | '/api/og/certificates'
    | '/api/og/feedback'
    | '/api/og/feelings'
    | '/api/og/kahoot'
    | '/api/og/polls'
    | '/api/og/testimonials'
    | '/certificates/verify/$id'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/_authed/certificates/'
    | '/_authed/schedule/'
    | '/_authed/testimonials/'
    | '/api/og/'
    | '/_authed/party/feedback-host/history'
    | '/_authed/party/feelings/history'
    | '/_authed/party/kahoot-host/history'
    | '/_authed/party/polls/history'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/_authed/party/feedback-host/'
    | '/_authed/party/feelings/'
    | '/_authed/party/kahoot-host/'
    | '/_authed/party/polls/'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  McpRoute: typeof McpRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTableRoute: typeof DemoTableRoute
  PartyFeedbackClientRoute: typeof PartyFeedbackClientRoute
  PartyKahootPlayerRoute: typeof PartyKahootPlayerRoute
  PartyKahootProjectorRoute: typeof PartyKahootProjectorRoute
  PartyPollVoterRoute: typeof PartyPollVoterRoute
  TestimonialsSubmitRoute: typeof TestimonialsSubmitRoute
  TestimonialsWallRoute: typeof TestimonialsWallRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiInternalFeedbackRoute: typeof ApiInternalFeedbackRoute
  ApiInternalFeelingsRoute: typeof ApiInternalFeelingsRoute
  ApiInternalKahootRoute: typeof ApiInternalKahootRoute
  ApiInternalPollsRoute: typeof ApiInternalPollsRoute
  ApiInternalTestimonialsRoute: typeof ApiInternalTestimonialsRoute
  ApiOgCertificatesRoute: typeof ApiOgCertificatesRoute
  ApiOgFeedbackRoute: typeof ApiOgFeedbackRoute
  ApiOgFeelingsRoute: typeof ApiOgFeelingsRoute
  ApiOgKahootRoute: typeof ApiOgKahootRoute
  ApiOgPollsRoute: typeof ApiOgPollsRoute
  ApiOgTestimonialsRoute: typeof ApiOgTestimonialsRoute
  CertificatesVerifyIdRoute: typeof CertificatesVerifyIdRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiOgIndexRoute: typeof ApiOgIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/wall': {
      id: '/testimonials/wall'
      path: '/testimonials/wall'
      fullPath: '/testimonials/wall'
      preLoaderRoute: typeof TestimonialsWallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials/submit': {
      id: '/testimonials/submit'
      path: '/testimonials/submit'
      fullPath: '/testimonials/submit'
      preLoaderRoute: typeof TestimonialsSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/poll-voter': {
      id: '/party/poll-voter'
      path: '/party/poll-voter'
      fullPath: '/party/poll-voter'
      preLoaderRoute: typeof PartyPollVoterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/kahoot-projector': {
      id: '/party/kahoot-projector'
      path: '/party/kahoot-projector'
      fullPath: '/party/kahoot-projector'
      preLoaderRoute: typeof PartyKahootProjectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/kahoot-player': {
      id: '/party/kahoot-player'
      path: '/party/kahoot-player'
      fullPath: '/party/kahoot-player'
      preLoaderRoute: typeof PartyKahootPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/feedback-client': {
      id: '/party/feedback-client'
      path: '/party/feedback-client'
      fullPath: '/party/feedback-client'
      preLoaderRoute: typeof PartyFeedbackClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/testimonials': {
      id: '/_authed/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof AuthedTestimonialsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/schedule': {
      id: '/_authed/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthedScheduleRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/certificates': {
      id: '/_authed/certificates'
      path: '/certificates'
      fullPath: '/certificates'
      preLoaderRoute: typeof AuthedCertificatesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/og/': {
      id: '/api/og/'
      path: '/api/og'
      fullPath: '/api/og/'
      preLoaderRoute: typeof ApiOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/testimonials/': {
      id: '/_authed/testimonials/'
      path: '/'
      fullPath: '/testimonials/'
      preLoaderRoute: typeof AuthedTestimonialsIndexRouteImport
      parentRoute: typeof AuthedTestimonialsRoute
    }
    '/_authed/schedule/': {
      id: '/_authed/schedule/'
      path: '/'
      fullPath: '/schedule/'
      preLoaderRoute: typeof AuthedScheduleIndexRouteImport
      parentRoute: typeof AuthedScheduleRoute
    }
    '/_authed/certificates/': {
      id: '/_authed/certificates/'
      path: '/'
      fullPath: '/certificates/'
      preLoaderRoute: typeof AuthedCertificatesIndexRouteImport
      parentRoute: typeof AuthedCertificatesRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificates/verify/$id': {
      id: '/certificates/verify/$id'
      path: '/certificates/verify/$id'
      fullPath: '/certificates/verify/$id'
      preLoaderRoute: typeof CertificatesVerifyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/testimonials': {
      id: '/api/og/testimonials'
      path: '/api/og/testimonials'
      fullPath: '/api/og/testimonials'
      preLoaderRoute: typeof ApiOgTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/polls': {
      id: '/api/og/polls'
      path: '/api/og/polls'
      fullPath: '/api/og/polls'
      preLoaderRoute: typeof ApiOgPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/kahoot': {
      id: '/api/og/kahoot'
      path: '/api/og/kahoot'
      fullPath: '/api/og/kahoot'
      preLoaderRoute: typeof ApiOgKahootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/feelings': {
      id: '/api/og/feelings'
      path: '/api/og/feelings'
      fullPath: '/api/og/feelings'
      preLoaderRoute: typeof ApiOgFeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/feedback': {
      id: '/api/og/feedback'
      path: '/api/og/feedback'
      fullPath: '/api/og/feedback'
      preLoaderRoute: typeof ApiOgFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/certificates': {
      id: '/api/og/certificates'
      path: '/api/og/certificates'
      fullPath: '/api/og/certificates'
      preLoaderRoute: typeof ApiOgCertificatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/testimonials': {
      id: '/api/internal/testimonials'
      path: '/api/internal/testimonials'
      fullPath: '/api/internal/testimonials'
      preLoaderRoute: typeof ApiInternalTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/polls': {
      id: '/api/internal/polls'
      path: '/api/internal/polls'
      fullPath: '/api/internal/polls'
      preLoaderRoute: typeof ApiInternalPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/kahoot': {
      id: '/api/internal/kahoot'
      path: '/api/internal/kahoot'
      fullPath: '/api/internal/kahoot'
      preLoaderRoute: typeof ApiInternalKahootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/feelings': {
      id: '/api/internal/feelings'
      path: '/api/internal/feelings'
      fullPath: '/api/internal/feelings'
      preLoaderRoute: typeof ApiInternalFeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/internal/feedback': {
      id: '/api/internal/feedback'
      path: '/api/internal/feedback'
      fullPath: '/api/internal/feedback'
      preLoaderRoute: typeof ApiInternalFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/testimonials/host': {
      id: '/_authed/testimonials/host'
      path: '/host'
      fullPath: '/testimonials/host'
      preLoaderRoute: typeof AuthedTestimonialsHostRouteImport
      parentRoute: typeof AuthedTestimonialsRoute
    }
    '/_authed/testimonials/history': {
      id: '/_authed/testimonials/history'
      path: '/history'
      fullPath: '/testimonials/history'
      preLoaderRoute: typeof AuthedTestimonialsHistoryRouteImport
      parentRoute: typeof AuthedTestimonialsRoute
    }
    '/_authed/schedule/new': {
      id: '/_authed/schedule/new'
      path: '/new'
      fullPath: '/schedule/new'
      preLoaderRoute: typeof AuthedScheduleNewRouteImport
      parentRoute: typeof AuthedScheduleRoute
    }
    '/_authed/party/polls': {
      id: '/_authed/party/polls'
      path: '/party/polls'
      fullPath: '/party/polls'
      preLoaderRoute: typeof AuthedPartyPollsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/party/kahoot-host': {
      id: '/_authed/party/kahoot-host'
      path: '/party/kahoot-host'
      fullPath: '/party/kahoot-host'
      preLoaderRoute: typeof AuthedPartyKahootHostRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/party/feelings': {
      id: '/_authed/party/feelings'
      path: '/party/feelings'
      fullPath: '/party/feelings'
      preLoaderRoute: typeof AuthedPartyFeelingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/party/feedback-host': {
      id: '/_authed/party/feedback-host'
      path: '/party/feedback-host'
      fullPath: '/party/feedback-host'
      preLoaderRoute: typeof AuthedPartyFeedbackHostRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/certificates/settings': {
      id: '/_authed/certificates/settings'
      path: '/settings'
      fullPath: '/certificates/settings'
      preLoaderRoute: typeof AuthedCertificatesSettingsRouteImport
      parentRoute: typeof AuthedCertificatesRoute
    }
    '/_authed/certificates/send': {
      id: '/_authed/certificates/send'
      path: '/send'
      fullPath: '/certificates/send'
      preLoaderRoute: typeof AuthedCertificatesSendRouteImport
      parentRoute: typeof AuthedCertificatesRoute
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr/'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/party/polls/': {
      id: '/_authed/party/polls/'
      path: '/'
      fullPath: '/party/polls/'
      preLoaderRoute: typeof AuthedPartyPollsIndexRouteImport
      parentRoute: typeof AuthedPartyPollsRoute
    }
    '/_authed/party/kahoot-host/': {
      id: '/_authed/party/kahoot-host/'
      path: '/'
      fullPath: '/party/kahoot-host/'
      preLoaderRoute: typeof AuthedPartyKahootHostIndexRouteImport
      parentRoute: typeof AuthedPartyKahootHostRoute
    }
    '/_authed/party/feelings/': {
      id: '/_authed/party/feelings/'
      path: '/'
      fullPath: '/party/feelings/'
      preLoaderRoute: typeof AuthedPartyFeelingsIndexRouteImport
      parentRoute: typeof AuthedPartyFeelingsRoute
    }
    '/_authed/party/feedback-host/': {
      id: '/_authed/party/feedback-host/'
      path: '/'
      fullPath: '/party/feedback-host/'
      preLoaderRoute: typeof AuthedPartyFeedbackHostIndexRouteImport
      parentRoute: typeof AuthedPartyFeedbackHostRoute
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/party/polls/history': {
      id: '/_authed/party/polls/history'
      path: '/history'
      fullPath: '/party/polls/history'
      preLoaderRoute: typeof AuthedPartyPollsHistoryRouteImport
      parentRoute: typeof AuthedPartyPollsRoute
    }
    '/_authed/party/kahoot-host/history': {
      id: '/_authed/party/kahoot-host/history'
      path: '/history'
      fullPath: '/party/kahoot-host/history'
      preLoaderRoute: typeof AuthedPartyKahootHostHistoryRouteImport
      parentRoute: typeof AuthedPartyKahootHostRoute
    }
    '/_authed/party/feelings/history': {
      id: '/_authed/party/feelings/history'
      path: '/history'
      fullPath: '/party/feelings/history'
      preLoaderRoute: typeof AuthedPartyFeelingsHistoryRouteImport
      parentRoute: typeof AuthedPartyFeelingsRoute
    }
    '/_authed/party/feedback-host/history': {
      id: '/_authed/party/feedback-host/history'
      path: '/history'
      fullPath: '/party/feedback-host/history'
      preLoaderRoute: typeof AuthedPartyFeedbackHostHistoryRouteImport
      parentRoute: typeof AuthedPartyFeedbackHostRoute
    }
  }
}

interface AuthedCertificatesRouteChildren {
  AuthedCertificatesSendRoute: typeof AuthedCertificatesSendRoute
  AuthedCertificatesSettingsRoute: typeof AuthedCertificatesSettingsRoute
  AuthedCertificatesIndexRoute: typeof AuthedCertificatesIndexRoute
}

const AuthedCertificatesRouteChildren: AuthedCertificatesRouteChildren = {
  AuthedCertificatesSendRoute: AuthedCertificatesSendRoute,
  AuthedCertificatesSettingsRoute: AuthedCertificatesSettingsRoute,
  AuthedCertificatesIndexRoute: AuthedCertificatesIndexRoute,
}

const AuthedCertificatesRouteWithChildren =
  AuthedCertificatesRoute._addFileChildren(AuthedCertificatesRouteChildren)

interface AuthedScheduleRouteChildren {
  AuthedScheduleNewRoute: typeof AuthedScheduleNewRoute
  AuthedScheduleIndexRoute: typeof AuthedScheduleIndexRoute
}

const AuthedScheduleRouteChildren: AuthedScheduleRouteChildren = {
  AuthedScheduleNewRoute: AuthedScheduleNewRoute,
  AuthedScheduleIndexRoute: AuthedScheduleIndexRoute,
}

const AuthedScheduleRouteWithChildren = AuthedScheduleRoute._addFileChildren(
  AuthedScheduleRouteChildren,
)

interface AuthedTestimonialsRouteChildren {
  AuthedTestimonialsHistoryRoute: typeof AuthedTestimonialsHistoryRoute
  AuthedTestimonialsHostRoute: typeof AuthedTestimonialsHostRoute
  AuthedTestimonialsIndexRoute: typeof AuthedTestimonialsIndexRoute
}

const AuthedTestimonialsRouteChildren: AuthedTestimonialsRouteChildren = {
  AuthedTestimonialsHistoryRoute: AuthedTestimonialsHistoryRoute,
  AuthedTestimonialsHostRoute: AuthedTestimonialsHostRoute,
  AuthedTestimonialsIndexRoute: AuthedTestimonialsIndexRoute,
}

const AuthedTestimonialsRouteWithChildren =
  AuthedTestimonialsRoute._addFileChildren(AuthedTestimonialsRouteChildren)

interface AuthedPartyFeedbackHostRouteChildren {
  AuthedPartyFeedbackHostHistoryRoute: typeof AuthedPartyFeedbackHostHistoryRoute
  AuthedPartyFeedbackHostIndexRoute: typeof AuthedPartyFeedbackHostIndexRoute
}

const AuthedPartyFeedbackHostRouteChildren: AuthedPartyFeedbackHostRouteChildren =
  {
    AuthedPartyFeedbackHostHistoryRoute: AuthedPartyFeedbackHostHistoryRoute,
    AuthedPartyFeedbackHostIndexRoute: AuthedPartyFeedbackHostIndexRoute,
  }

const AuthedPartyFeedbackHostRouteWithChildren =
  AuthedPartyFeedbackHostRoute._addFileChildren(
    AuthedPartyFeedbackHostRouteChildren,
  )

interface AuthedPartyFeelingsRouteChildren {
  AuthedPartyFeelingsHistoryRoute: typeof AuthedPartyFeelingsHistoryRoute
  AuthedPartyFeelingsIndexRoute: typeof AuthedPartyFeelingsIndexRoute
}

const AuthedPartyFeelingsRouteChildren: AuthedPartyFeelingsRouteChildren = {
  AuthedPartyFeelingsHistoryRoute: AuthedPartyFeelingsHistoryRoute,
  AuthedPartyFeelingsIndexRoute: AuthedPartyFeelingsIndexRoute,
}

const AuthedPartyFeelingsRouteWithChildren =
  AuthedPartyFeelingsRoute._addFileChildren(AuthedPartyFeelingsRouteChildren)

interface AuthedPartyKahootHostRouteChildren {
  AuthedPartyKahootHostHistoryRoute: typeof AuthedPartyKahootHostHistoryRoute
  AuthedPartyKahootHostIndexRoute: typeof AuthedPartyKahootHostIndexRoute
}

const AuthedPartyKahootHostRouteChildren: AuthedPartyKahootHostRouteChildren = {
  AuthedPartyKahootHostHistoryRoute: AuthedPartyKahootHostHistoryRoute,
  AuthedPartyKahootHostIndexRoute: AuthedPartyKahootHostIndexRoute,
}

const AuthedPartyKahootHostRouteWithChildren =
  AuthedPartyKahootHostRoute._addFileChildren(
    AuthedPartyKahootHostRouteChildren,
  )

interface AuthedPartyPollsRouteChildren {
  AuthedPartyPollsHistoryRoute: typeof AuthedPartyPollsHistoryRoute
  AuthedPartyPollsIndexRoute: typeof AuthedPartyPollsIndexRoute
}

const AuthedPartyPollsRouteChildren: AuthedPartyPollsRouteChildren = {
  AuthedPartyPollsHistoryRoute: AuthedPartyPollsHistoryRoute,
  AuthedPartyPollsIndexRoute: AuthedPartyPollsIndexRoute,
}

const AuthedPartyPollsRouteWithChildren =
  AuthedPartyPollsRoute._addFileChildren(AuthedPartyPollsRouteChildren)

interface AuthedRouteChildren {
  AuthedCertificatesRoute: typeof AuthedCertificatesRouteWithChildren
  AuthedScheduleRoute: typeof AuthedScheduleRouteWithChildren
  AuthedTestimonialsRoute: typeof AuthedTestimonialsRouteWithChildren
  AuthedPartyFeedbackHostRoute: typeof AuthedPartyFeedbackHostRouteWithChildren
  AuthedPartyFeelingsRoute: typeof AuthedPartyFeelingsRouteWithChildren
  AuthedPartyKahootHostRoute: typeof AuthedPartyKahootHostRouteWithChildren
  AuthedPartyPollsRoute: typeof AuthedPartyPollsRouteWithChildren
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCertificatesRoute: AuthedCertificatesRouteWithChildren,
  AuthedScheduleRoute: AuthedScheduleRouteWithChildren,
  AuthedTestimonialsRoute: AuthedTestimonialsRouteWithChildren,
  AuthedPartyFeedbackHostRoute: AuthedPartyFeedbackHostRouteWithChildren,
  AuthedPartyFeelingsRoute: AuthedPartyFeelingsRouteWithChildren,
  AuthedPartyKahootHostRoute: AuthedPartyKahootHostRouteWithChildren,
  AuthedPartyPollsRoute: AuthedPartyPollsRouteWithChildren,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  McpRoute: McpRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTableRoute: DemoTableRoute,
  PartyFeedbackClientRoute: PartyFeedbackClientRoute,
  PartyKahootPlayerRoute: PartyKahootPlayerRoute,
  PartyKahootProjectorRoute: PartyKahootProjectorRoute,
  PartyPollVoterRoute: PartyPollVoterRoute,
  TestimonialsSubmitRoute: TestimonialsSubmitRoute,
  TestimonialsWallRoute: TestimonialsWallRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiInternalFeedbackRoute: ApiInternalFeedbackRoute,
  ApiInternalFeelingsRoute: ApiInternalFeelingsRoute,
  ApiInternalKahootRoute: ApiInternalKahootRoute,
  ApiInternalPollsRoute: ApiInternalPollsRoute,
  ApiInternalTestimonialsRoute: ApiInternalTestimonialsRoute,
  ApiOgCertificatesRoute: ApiOgCertificatesRoute,
  ApiOgFeedbackRoute: ApiOgFeedbackRoute,
  ApiOgFeelingsRoute: ApiOgFeelingsRoute,
  ApiOgKahootRoute: ApiOgKahootRoute,
  ApiOgPollsRoute: ApiOgPollsRoute,
  ApiOgTestimonialsRoute: ApiOgTestimonialsRoute,
  CertificatesVerifyIdRoute: CertificatesVerifyIdRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiOgIndexRoute: ApiOgIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
