/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as R404RouteImport } from './routes/$404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartyPollsRouteImport } from './routes/party.polls'
import { Route as PartyPollVoterRouteImport } from './routes/party.poll-voter'
import { Route as PartyKahootProjectorRouteImport } from './routes/party.kahoot-projector'
import { Route as PartyKahootPlayerRouteImport } from './routes/party.kahoot-player'
import { Route as PartyKahootHostRouteImport } from './routes/party.kahoot-host'
import { Route as PartyFeelingsRouteImport } from './routes/party.feelings'
import { Route as PartyFeedbackHostRouteImport } from './routes/party.feedback-host'
import { Route as PartyFeedbackClientRouteImport } from './routes/party.feedback-client'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as DemoNeonRouteImport } from './routes/demo/neon'
import { Route as DemoMcpTodosRouteImport } from './routes/demo/mcp-todos'
import { Route as DemoDrizzleRouteImport } from './routes/demo/drizzle'
import { Route as ApiOgIndexRouteImport } from './routes/api/og/index'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'
import { Route as DemoStartApiRequestRouteImport } from './routes/demo/start.api-request'
import { Route as DemoApiNamesRouteImport } from './routes/demo/api.names'
import { Route as DemoApiMcpTodosRouteImport } from './routes/demo/api.mcp-todos'
import { Route as ApiOgPollsRouteImport } from './routes/api/og/polls'
import { Route as ApiOgKahootRouteImport } from './routes/api/og/kahoot'
import { Route as ApiOgFeelingsRouteImport } from './routes/api/og/feelings'
import { Route as ApiOgFeedbackRouteImport } from './routes/api/og/feedback'
import { Route as DemoStartSsrIndexRouteImport } from './routes/demo/start.ssr.index'
import { Route as DemoStartSsrSpaModeRouteImport } from './routes/demo/start.ssr.spa-mode'
import { Route as DemoStartSsrFullSsrRouteImport } from './routes/demo/start.ssr.full-ssr'
import { Route as DemoStartSsrDataOnlyRouteImport } from './routes/demo/start.ssr.data-only'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/$404',
  path: '/$404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPollsRoute = PartyPollsRouteImport.update({
  id: '/party/polls',
  path: '/party/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyPollVoterRoute = PartyPollVoterRouteImport.update({
  id: '/party/poll-voter',
  path: '/party/poll-voter',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyKahootProjectorRoute = PartyKahootProjectorRouteImport.update({
  id: '/party/kahoot-projector',
  path: '/party/kahoot-projector',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyKahootPlayerRoute = PartyKahootPlayerRouteImport.update({
  id: '/party/kahoot-player',
  path: '/party/kahoot-player',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyKahootHostRoute = PartyKahootHostRouteImport.update({
  id: '/party/kahoot-host',
  path: '/party/kahoot-host',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyFeelingsRoute = PartyFeelingsRouteImport.update({
  id: '/party/feelings',
  path: '/party/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyFeedbackHostRoute = PartyFeedbackHostRouteImport.update({
  id: '/party/feedback-host',
  path: '/party/feedback-host',
  getParentRoute: () => rootRouteImport,
} as any)
const PartyFeedbackClientRoute = PartyFeedbackClientRouteImport.update({
  id: '/party/feedback-client',
  path: '/party/feedback-client',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoNeonRoute = DemoNeonRouteImport.update({
  id: '/demo/neon',
  path: '/demo/neon',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoDrizzleRoute = DemoDrizzleRouteImport.update({
  id: '/demo/drizzle',
  path: '/demo/drizzle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgIndexRoute = ApiOgIndexRouteImport.update({
  id: '/api/og/',
  path: '/api/og/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartApiRequestRoute = DemoStartApiRequestRouteImport.update({
  id: '/demo/start/api-request',
  path: '/demo/start/api-request',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiNamesRoute = DemoApiNamesRouteImport.update({
  id: '/demo/api/names',
  path: '/demo/api/names',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoApiMcpTodosRoute = DemoApiMcpTodosRouteImport.update({
  id: '/demo/api/mcp-todos',
  path: '/demo/api/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgPollsRoute = ApiOgPollsRouteImport.update({
  id: '/api/og/polls',
  path: '/api/og/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgKahootRoute = ApiOgKahootRouteImport.update({
  id: '/api/og/kahoot',
  path: '/api/og/kahoot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgFeelingsRoute = ApiOgFeelingsRouteImport.update({
  id: '/api/og/feelings',
  path: '/api/og/feelings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgFeedbackRoute = ApiOgFeedbackRouteImport.update({
  id: '/api/og/feedback',
  path: '/api/og/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrIndexRoute = DemoStartSsrIndexRouteImport.update({
  id: '/demo/start/ssr/',
  path: '/demo/start/ssr/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrSpaModeRoute = DemoStartSsrSpaModeRouteImport.update({
  id: '/demo/start/ssr/spa-mode',
  path: '/demo/start/ssr/spa-mode',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrFullSsrRoute = DemoStartSsrFullSsrRouteImport.update({
  id: '/demo/start/ssr/full-ssr',
  path: '/demo/start/ssr/full-ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStartSsrDataOnlyRoute = DemoStartSsrDataOnlyRouteImport.update({
  id: '/demo/start/ssr/data-only',
  path: '/demo/start/ssr/data-only',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/mcp': typeof McpRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/party/feedback-client': typeof PartyFeedbackClientRoute
  '/party/feedback-host': typeof PartyFeedbackHostRoute
  '/party/feelings': typeof PartyFeelingsRoute
  '/party/kahoot-host': typeof PartyKahootHostRoute
  '/party/kahoot-player': typeof PartyKahootPlayerRoute
  '/party/kahoot-projector': typeof PartyKahootProjectorRoute
  '/party/poll-voter': typeof PartyPollVoterRoute
  '/party/polls': typeof PartyPollsRoute
  '/api/og/feedback': typeof ApiOgFeedbackRoute
  '/api/og/feelings': typeof ApiOgFeelingsRoute
  '/api/og/kahoot': typeof ApiOgKahootRoute
  '/api/og/polls': typeof ApiOgPollsRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/og': typeof ApiOgIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/mcp': typeof McpRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/party/feedback-client': typeof PartyFeedbackClientRoute
  '/party/feedback-host': typeof PartyFeedbackHostRoute
  '/party/feelings': typeof PartyFeelingsRoute
  '/party/kahoot-host': typeof PartyKahootHostRoute
  '/party/kahoot-player': typeof PartyKahootPlayerRoute
  '/party/kahoot-projector': typeof PartyKahootProjectorRoute
  '/party/poll-voter': typeof PartyPollVoterRoute
  '/party/polls': typeof PartyPollsRoute
  '/api/og/feedback': typeof ApiOgFeedbackRoute
  '/api/og/feelings': typeof ApiOgFeelingsRoute
  '/api/og/kahoot': typeof ApiOgKahootRoute
  '/api/og/polls': typeof ApiOgPollsRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/og': typeof ApiOgIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr': typeof DemoStartSsrIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$404': typeof R404Route
  '/mcp': typeof McpRoute
  '/demo/drizzle': typeof DemoDrizzleRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/demo/neon': typeof DemoNeonRoute
  '/demo/table': typeof DemoTableRoute
  '/party/feedback-client': typeof PartyFeedbackClientRoute
  '/party/feedback-host': typeof PartyFeedbackHostRoute
  '/party/feelings': typeof PartyFeelingsRoute
  '/party/kahoot-host': typeof PartyKahootHostRoute
  '/party/kahoot-player': typeof PartyKahootPlayerRoute
  '/party/kahoot-projector': typeof PartyKahootProjectorRoute
  '/party/poll-voter': typeof PartyPollVoterRoute
  '/party/polls': typeof PartyPollsRoute
  '/api/og/feedback': typeof ApiOgFeedbackRoute
  '/api/og/feelings': typeof ApiOgFeelingsRoute
  '/api/og/kahoot': typeof ApiOgKahootRoute
  '/api/og/polls': typeof ApiOgPollsRoute
  '/demo/api/mcp-todos': typeof DemoApiMcpTodosRoute
  '/demo/api/names': typeof DemoApiNamesRoute
  '/demo/start/api-request': typeof DemoStartApiRequestRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
  '/api/og/': typeof ApiOgIndexRoute
  '/demo/start/ssr/data-only': typeof DemoStartSsrDataOnlyRoute
  '/demo/start/ssr/full-ssr': typeof DemoStartSsrFullSsrRoute
  '/demo/start/ssr/spa-mode': typeof DemoStartSsrSpaModeRoute
  '/demo/start/ssr/': typeof DemoStartSsrIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$404'
    | '/mcp'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/table'
    | '/party/feedback-client'
    | '/party/feedback-host'
    | '/party/feelings'
    | '/party/kahoot-host'
    | '/party/kahoot-player'
    | '/party/kahoot-projector'
    | '/party/poll-voter'
    | '/party/polls'
    | '/api/og/feedback'
    | '/api/og/feelings'
    | '/api/og/kahoot'
    | '/api/og/polls'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/og'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$404'
    | '/mcp'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/table'
    | '/party/feedback-client'
    | '/party/feedback-host'
    | '/party/feelings'
    | '/party/kahoot-host'
    | '/party/kahoot-player'
    | '/party/kahoot-projector'
    | '/party/poll-voter'
    | '/party/polls'
    | '/api/og/feedback'
    | '/api/og/feelings'
    | '/api/og/kahoot'
    | '/api/og/polls'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/og'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr'
  id:
    | '__root__'
    | '/'
    | '/$404'
    | '/mcp'
    | '/demo/drizzle'
    | '/demo/mcp-todos'
    | '/demo/neon'
    | '/demo/table'
    | '/party/feedback-client'
    | '/party/feedback-host'
    | '/party/feelings'
    | '/party/kahoot-host'
    | '/party/kahoot-player'
    | '/party/kahoot-projector'
    | '/party/poll-voter'
    | '/party/polls'
    | '/api/og/feedback'
    | '/api/og/feelings'
    | '/api/og/kahoot'
    | '/api/og/polls'
    | '/demo/api/mcp-todos'
    | '/demo/api/names'
    | '/demo/start/api-request'
    | '/demo/start/server-funcs'
    | '/api/og/'
    | '/demo/start/ssr/data-only'
    | '/demo/start/ssr/full-ssr'
    | '/demo/start/ssr/spa-mode'
    | '/demo/start/ssr/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  McpRoute: typeof McpRoute
  DemoDrizzleRoute: typeof DemoDrizzleRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  DemoNeonRoute: typeof DemoNeonRoute
  DemoTableRoute: typeof DemoTableRoute
  PartyFeedbackClientRoute: typeof PartyFeedbackClientRoute
  PartyFeedbackHostRoute: typeof PartyFeedbackHostRoute
  PartyFeelingsRoute: typeof PartyFeelingsRoute
  PartyKahootHostRoute: typeof PartyKahootHostRoute
  PartyKahootPlayerRoute: typeof PartyKahootPlayerRoute
  PartyKahootProjectorRoute: typeof PartyKahootProjectorRoute
  PartyPollVoterRoute: typeof PartyPollVoterRoute
  PartyPollsRoute: typeof PartyPollsRoute
  ApiOgFeedbackRoute: typeof ApiOgFeedbackRoute
  ApiOgFeelingsRoute: typeof ApiOgFeelingsRoute
  ApiOgKahootRoute: typeof ApiOgKahootRoute
  ApiOgPollsRoute: typeof ApiOgPollsRoute
  DemoApiMcpTodosRoute: typeof DemoApiMcpTodosRoute
  DemoApiNamesRoute: typeof DemoApiNamesRoute
  DemoStartApiRequestRoute: typeof DemoStartApiRequestRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
  ApiOgIndexRoute: typeof ApiOgIndexRoute
  DemoStartSsrDataOnlyRoute: typeof DemoStartSsrDataOnlyRoute
  DemoStartSsrFullSsrRoute: typeof DemoStartSsrFullSsrRoute
  DemoStartSsrSpaModeRoute: typeof DemoStartSsrSpaModeRoute
  DemoStartSsrIndexRoute: typeof DemoStartSsrIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$404': {
      id: '/$404'
      path: '/$404'
      fullPath: '/$404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/polls': {
      id: '/party/polls'
      path: '/party/polls'
      fullPath: '/party/polls'
      preLoaderRoute: typeof PartyPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/poll-voter': {
      id: '/party/poll-voter'
      path: '/party/poll-voter'
      fullPath: '/party/poll-voter'
      preLoaderRoute: typeof PartyPollVoterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/kahoot-projector': {
      id: '/party/kahoot-projector'
      path: '/party/kahoot-projector'
      fullPath: '/party/kahoot-projector'
      preLoaderRoute: typeof PartyKahootProjectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/kahoot-player': {
      id: '/party/kahoot-player'
      path: '/party/kahoot-player'
      fullPath: '/party/kahoot-player'
      preLoaderRoute: typeof PartyKahootPlayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/kahoot-host': {
      id: '/party/kahoot-host'
      path: '/party/kahoot-host'
      fullPath: '/party/kahoot-host'
      preLoaderRoute: typeof PartyKahootHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/feelings': {
      id: '/party/feelings'
      path: '/party/feelings'
      fullPath: '/party/feelings'
      preLoaderRoute: typeof PartyFeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/feedback-host': {
      id: '/party/feedback-host'
      path: '/party/feedback-host'
      fullPath: '/party/feedback-host'
      preLoaderRoute: typeof PartyFeedbackHostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/party/feedback-client': {
      id: '/party/feedback-client'
      path: '/party/feedback-client'
      fullPath: '/party/feedback-client'
      preLoaderRoute: typeof PartyFeedbackClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/neon': {
      id: '/demo/neon'
      path: '/demo/neon'
      fullPath: '/demo/neon'
      preLoaderRoute: typeof DemoNeonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/drizzle': {
      id: '/demo/drizzle'
      path: '/demo/drizzle'
      fullPath: '/demo/drizzle'
      preLoaderRoute: typeof DemoDrizzleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/': {
      id: '/api/og/'
      path: '/api/og'
      fullPath: '/api/og'
      preLoaderRoute: typeof ApiOgIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/api-request': {
      id: '/demo/start/api-request'
      path: '/demo/start/api-request'
      fullPath: '/demo/start/api-request'
      preLoaderRoute: typeof DemoStartApiRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/names': {
      id: '/demo/api/names'
      path: '/demo/api/names'
      fullPath: '/demo/api/names'
      preLoaderRoute: typeof DemoApiNamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/api/mcp-todos': {
      id: '/demo/api/mcp-todos'
      path: '/demo/api/mcp-todos'
      fullPath: '/demo/api/mcp-todos'
      preLoaderRoute: typeof DemoApiMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/polls': {
      id: '/api/og/polls'
      path: '/api/og/polls'
      fullPath: '/api/og/polls'
      preLoaderRoute: typeof ApiOgPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/kahoot': {
      id: '/api/og/kahoot'
      path: '/api/og/kahoot'
      fullPath: '/api/og/kahoot'
      preLoaderRoute: typeof ApiOgKahootRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/feelings': {
      id: '/api/og/feelings'
      path: '/api/og/feelings'
      fullPath: '/api/og/feelings'
      preLoaderRoute: typeof ApiOgFeelingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/feedback': {
      id: '/api/og/feedback'
      path: '/api/og/feedback'
      fullPath: '/api/og/feedback'
      preLoaderRoute: typeof ApiOgFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/': {
      id: '/demo/start/ssr/'
      path: '/demo/start/ssr'
      fullPath: '/demo/start/ssr'
      preLoaderRoute: typeof DemoStartSsrIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/spa-mode': {
      id: '/demo/start/ssr/spa-mode'
      path: '/demo/start/ssr/spa-mode'
      fullPath: '/demo/start/ssr/spa-mode'
      preLoaderRoute: typeof DemoStartSsrSpaModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/full-ssr': {
      id: '/demo/start/ssr/full-ssr'
      path: '/demo/start/ssr/full-ssr'
      fullPath: '/demo/start/ssr/full-ssr'
      preLoaderRoute: typeof DemoStartSsrFullSsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/start/ssr/data-only': {
      id: '/demo/start/ssr/data-only'
      path: '/demo/start/ssr/data-only'
      fullPath: '/demo/start/ssr/data-only'
      preLoaderRoute: typeof DemoStartSsrDataOnlyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  McpRoute: McpRoute,
  DemoDrizzleRoute: DemoDrizzleRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  DemoNeonRoute: DemoNeonRoute,
  DemoTableRoute: DemoTableRoute,
  PartyFeedbackClientRoute: PartyFeedbackClientRoute,
  PartyFeedbackHostRoute: PartyFeedbackHostRoute,
  PartyFeelingsRoute: PartyFeelingsRoute,
  PartyKahootHostRoute: PartyKahootHostRoute,
  PartyKahootPlayerRoute: PartyKahootPlayerRoute,
  PartyKahootProjectorRoute: PartyKahootProjectorRoute,
  PartyPollVoterRoute: PartyPollVoterRoute,
  PartyPollsRoute: PartyPollsRoute,
  ApiOgFeedbackRoute: ApiOgFeedbackRoute,
  ApiOgFeelingsRoute: ApiOgFeelingsRoute,
  ApiOgKahootRoute: ApiOgKahootRoute,
  ApiOgPollsRoute: ApiOgPollsRoute,
  DemoApiMcpTodosRoute: DemoApiMcpTodosRoute,
  DemoApiNamesRoute: DemoApiNamesRoute,
  DemoStartApiRequestRoute: DemoStartApiRequestRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
  ApiOgIndexRoute: ApiOgIndexRoute,
  DemoStartSsrDataOnlyRoute: DemoStartSsrDataOnlyRoute,
  DemoStartSsrFullSsrRoute: DemoStartSsrFullSsrRoute,
  DemoStartSsrSpaModeRoute: DemoStartSsrSpaModeRoute,
  DemoStartSsrIndexRoute: DemoStartSsrIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
